import type { Era, Resources } from './game';

/**
 * Chronicle Entry - A single event in the civilization's history
 */
export interface ChronicleEntry {
  id: string;
  tick: number;
  era: Era;
  type: 'building' | 'era' | 'event' | 'combat' | 'milestone';
  title: string;
  description: string;
  icon?: string;
}

/**
 * Chronicle - Complete history of a civilization
 */
export interface Chronicle {
  civilizationName: string;
  startedAt: Date;
  entries: ChronicleEntry[];
  finalSummary?: string; // Generated by AI at game end
}

/**
 * Game Statistics - Metrics tracked during gameplay
 */
export interface GameStatistics {
  duration: number; // Total ticks played
  realTimePlayed: number; // Real time in seconds
  finalEra: Era;
  maxPopulation: number;
  totalBuildings: number;
  totalBattles: number;
  battlesWon: number;
  eventsEncountered: number;
  resourcesGathered: Resources;
}
